;
; File generated by cc65 v 2.15
;
	.fopt		compiler,"cc65 v 2.15"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.importzp	_FrameCount
	.importzp	_InputPort1
	.importzp	_InputPort1Prev
	.importzp	_VRAMUpdateReady
	.importzp	_Scroll
	.importzp	_BGDestAddr
	.importzp	_BGBuffer
	.import		_WaitFrame
	.import		_bankswitch
	.import		_flushBGBuffer
	.export		_endLoop
	.export		_i
	.export		_x
	.export		_y
	.export		_mapX
	.export		_mapY
	.export		_tileIndex
	.export		_tile
	.export		_tileIdx
	.export		_currentEntityId
	.export		_currentMetaSpriteId
	.export		_mapCurrentLine
	.export		_timer
	.export		_sprites
	.export		_titlePalette
	.export		_titleScreen
	.export		_copyTitleScreen
	.export		_mapPalette
	.export		_map
	.export		_mapLineCount
	.export		_copyBgLine
	.export		_fillBackground
	.export		_playerSpriteFrames
	.export		_drawMetaSprite
	.export		_drawSprite
	.export		_entities
	.export		_freeEntityList
	.export		_entityList
	.export		_missileList
	.export		_initEntityList
	.export		_pushEntity
	.export		_removeEntity
	.export		_popEntity
	.export		_bulletUpdate
	.export		_spawnBullet
	.export		_playerUpdate
	.export		_loadPalette
	.export		_main

.segment	"DATA"

_freeEntityList:
	.byte	$FF
_entityList:
	.byte	$FF
_missileList:
	.byte	$FF

.segment	"RODATA"

_titlePalette:
	.byte	$0F
	.byte	$16
	.byte	$27
	.byte	$06
	.byte	$0F
	.byte	$2D
	.byte	$2D
	.byte	$2D
	.byte	$0F
	.byte	$30
	.byte	$30
	.byte	$0F
	.byte	$0F
	.byte	$19
	.byte	$29
	.byte	$39
	.byte	$0F
	.byte	$16
	.byte	$05
	.byte	$27
	.byte	$0F
	.byte	$11
	.byte	$21
	.byte	$31
	.byte	$0F
	.byte	$15
	.byte	$25
	.byte	$35
	.byte	$0F
	.byte	$19
	.byte	$29
	.byte	$39
_titleScreen:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$85
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$87
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$B0
	.byte	$B1
	.byte	$00
	.byte	$88
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$86
	.byte	$87
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$C0
	.byte	$C1
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$20
	.byte	$21
	.byte	$22
	.byte	$23
	.byte	$24
	.byte	$25
	.byte	$26
	.byte	$27
	.byte	$28
	.byte	$29
	.byte	$2A
	.byte	$2B
	.byte	$2C
	.byte	$2D
	.byte	$82
	.byte	$83
	.byte	$84
	.byte	$26
	.byte	$27
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$30
	.byte	$31
	.byte	$32
	.byte	$33
	.byte	$34
	.byte	$35
	.byte	$36
	.byte	$37
	.byte	$38
	.byte	$39
	.byte	$3A
	.byte	$3B
	.byte	$3C
	.byte	$3D
	.byte	$92
	.byte	$93
	.byte	$94
	.byte	$36
	.byte	$37
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$47
	.byte	$48
	.byte	$49
	.byte	$4A
	.byte	$4B
	.byte	$4C
	.byte	$4D
	.byte	$A2
	.byte	$A3
	.byte	$A4
	.byte	$46
	.byte	$47
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$50
	.byte	$51
	.byte	$52
	.byte	$53
	.byte	$54
	.byte	$55
	.byte	$56
	.byte	$57
	.byte	$58
	.byte	$59
	.byte	$5A
	.byte	$5B
	.byte	$5C
	.byte	$5D
	.byte	$B2
	.byte	$B3
	.byte	$B4
	.byte	$56
	.byte	$57
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$60
	.byte	$61
	.byte	$62
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$68
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$6C
	.byte	$6D
	.byte	$C2
	.byte	$C3
	.byte	$C4
	.byte	$66
	.byte	$67
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$70
	.byte	$71
	.byte	$72
	.byte	$73
	.byte	$74
	.byte	$75
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$79
	.byte	$7A
	.byte	$7B
	.byte	$7C
	.byte	$7D
	.byte	$D2
	.byte	$D3
	.byte	$D4
	.byte	$76
	.byte	$77
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$90
	.byte	$91
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$A0
	.byte	$A1
	.byte	$00
	.byte	$98
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A7
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$95
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$A5
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A7
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$B5
	.byte	$B6
	.byte	$B7
	.byte	$B8
	.byte	$B8
	.byte	$00
	.byte	$00
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$B6
	.byte	$B9
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$BE
	.byte	$BC
	.byte	$BA
	.byte	$BB
	.byte	$B6
	.byte	$B7
	.byte	$C9
	.byte	$B5
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$00
	.byte	$C5
	.byte	$C6
	.byte	$C7
	.byte	$C8
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_mapPalette:
	.byte	$2A
	.byte	$00
	.byte	$10
	.byte	$20
	.byte	$2A
	.byte	$11
	.byte	$21
	.byte	$31
	.byte	$2A
	.byte	$15
	.byte	$25
	.byte	$35
	.byte	$2A
	.byte	$19
	.byte	$29
	.byte	$39
	.byte	$2A
	.byte	$16
	.byte	$05
	.byte	$27
	.byte	$2A
	.byte	$11
	.byte	$21
	.byte	$31
	.byte	$2A
	.byte	$15
	.byte	$25
	.byte	$35
	.byte	$2A
	.byte	$19
	.byte	$29
	.byte	$39
_map:
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$01
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$01
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$01
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
_mapLineCount:
	.word	$003B
_playerSpriteFrames:
	.byte	$00
	.byte	$00
	.byte	$20
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$21
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$30
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$31
	.byte	$00
	.byte	$7F
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$23
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$32
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$33
	.byte	$00
	.byte	$7F

.segment	"BSS"

.segment	"ZEROPAGE"
_endLoop:
	.res	1,$00
_i:
	.res	2,$00
_x:
	.res	2,$00
_y:
	.res	2,$00
_mapX:
	.res	2,$00
_mapY:
	.res	2,$00
_tileIndex:
	.res	2,$00
_tile:
	.res	1,$00
_tileIdx:
	.res	1,$00
_currentEntityId:
	.res	1,$00
_currentMetaSpriteId:
	.res	1,$00
_mapCurrentLine:
	.res	2,$00
_timer:
	.res	2,$00
.segment	"BSS"
.segment	"OAM"
_sprites:
	.res	256,$00
.segment	"BSS"
_entities:
	.res	144,$00

; ---------------------------------------------------------------
; void __near__ copyTitleScreen (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_copyTitleScreen: near

.segment	"CODE"

;
; PPU.vram.address = 0x20;
;
	lda     #$20
	sta     $2006
;
; PPU.vram.address = 0x00;
;
	lda     #$00
	sta     $2006
;
; for(i = 0; i < 30 * 32; i++) {
;
	sta     _i
	sta     _i+1
L03F7:	lda     _i+1
	cmp     #$03
	bne     L03FE
	lda     _i
	cmp     #$C0
L03FE:	bcs     L03F8
;
; PPU.vram.data = titleScreen[i];
;
	lda     #<(_titleScreen)
	sta     ptr1
	lda     #>(_titleScreen)
	clc
	adc     _i+1
	sta     ptr1+1
	ldy     _i
	lda     (ptr1),y
	sta     $2007
;
; for(i = 0; i < 30 * 32; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0400
	inx
L0400:	sta     _i
	stx     _i+1
	jmp     L03F7
;
; PPU.vram.address = 0x23;
;
L03F8:	lda     #$23
	sta     $2006
;
; PPU.vram.address = 0xC0;
;
	lda     #$C0
	sta     $2006
;
; for(i = 0; i < 40; i++) {
;
	lda     #$00
	sta     _i
	sta     _i+1
L040B:	lda     _i+1
	cmp     #$00
	bne     L0412
	lda     _i
	cmp     #$28
L0412:	bcs     L040C
;
; PPU.vram.data = 0x00;
;
	lda     #$00
	sta     $2007
;
; for(i = 0; i < 40; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0414
	inx
L0414:	sta     _i
	stx     _i+1
	jmp     L040B
;
; for(i = 40; i < 48; i++) {
;
L040C:	ldx     #$00
	lda     #$28
L0AD7:	sta     _i
	stx     _i+1
	lda     _i+1
	cmp     #$00
	bne     L041F
	lda     _i
	cmp     #$30
L041F:	bcs     L0419
;
; PPU.vram.data = 0xAA;
;
	lda     #$AA
	sta     $2007
;
; for(i = 40; i < 48; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0AD7
	inx
	jmp     L0AD7
;
; for(i = 48; i < 64; i++) {
;
L0419:	ldx     #$00
	lda     #$30
L0AD8:	sta     _i
	stx     _i+1
	lda     _i+1
	cmp     #$00
	bne     L042C
	lda     _i
	cmp     #$40
L042C:	bcs     L0426
;
; PPU.vram.data = 0x55;
;
	lda     #$55
	sta     $2007
;
; for(i = 48; i < 64; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0AD8
	inx
	jmp     L0AD8
;
; }
;
L0426:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ copyBgLine (__near__ const unsigned char *, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_copyBgLine: near

.segment	"BSS"

L0805:
	.res	2,$00

.segment	"CODE"

;
; void __fastcall__ copyBgLine(const uint8_t *buffer, uint16_t line) {
;
	jsr     pushax
;
; ptr = &BGBuffer;
;
	lda     #<(_BGBuffer)
	sta     L0805
	lda     #>(_BGBuffer)
	sta     L0805+1
;
; for(tile = 0; tile < 64; tile++) {
;
	lda     #$00
L0ADB:	sta     _tile
	cmp     #$40
	bcs     L0809
;
; tileIdx = buffer[line * 16 + ((tile & 0x1F) >> 1)] << 1;
;
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     shlax4
	sta     ptr1
	stx     ptr1+1
	lda     _tile
	and     #$1F
	lsr     a
	clc
	adc     ptr1
	pha
	tya
	adc     ptr1+1
	tax
	pla
	clc
	ldy     #$02
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	asl     a
	sta     _tileIdx
;
; if(tile & 0x1) {
;
	lda     _tile
	and     #$01
	beq     L0ADA
;
; ++tileIdx;
;
	inc     _tileIdx
;
; if(tile >= 32) {
;
L0ADA:	lda     _tile
	cmp     #$20
	bcc     L0818
;
; tileIdx += 0x10;
;
	lda     #$10
	clc
	adc     _tileIdx
	sta     _tileIdx
;
; (*ptr++) = tileIdx;
;
L0818:	lda     L0805
	ldx     L0805+1
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L081E
	inx
L081E:	sta     L0805
	stx     L0805+1
	lda     _tileIdx
	sta     (regsave),y
;
; for(tile = 0; tile < 64; tile++) {
;
	lda     _tile
	clc
	adc     #$01
	jmp     L0ADB
;
; }
;
L0809:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ fillBackground (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fillBackground: near

.segment	"CODE"

;
; mapCurrentLine = mapLineCount - 30;
;
	lda     _mapLineCount
	ldx     _mapLineCount+1
	sec
	sbc     #$1E
	bcs     L0823
	dex
L0823:	sta     _mapCurrentLine
	stx     _mapCurrentLine+1
;
; PPU.vram.address = 0x20;
;
	lda     #$20
	sta     $2006
;
; PPU.vram.address = 0x00;
;
	lda     #$00
	sta     $2006
;
; for(i = 0; i < 15; i++) {
;
	sta     _i
	sta     _i+1
L082A:	lda     _i+1
	cmp     #$00
	bne     L0831
	lda     _i
	cmp     #$0F
L0831:	bcs     L082B
;
; copyBgLine(map, mapCurrentLine + i);
;
	lda     #<(_map)
	ldx     #>(_map)
	jsr     pushax
	lda     _mapCurrentLine
	clc
	adc     _i
	pha
	lda     _mapCurrentLine+1
	adc     _i+1
	tax
	pla
	jsr     _copyBgLine
;
; flushBGBuffer();
;
	ldy     #$00
	jsr     _flushBGBuffer
;
; for(i = 0; i < 15; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0833
	inx
L0833:	sta     _i
	stx     _i+1
	jmp     L082A
;
; PPU.vram.address = 0x28;
;
L082B:	lda     #$28
	sta     $2006
;
; PPU.vram.address = 0x00;
;
	lda     #$00
	sta     $2006
;
; for(i = 0; i < 15; i++) {
;
	sta     _i
	sta     _i+1
L083E:	lda     _i+1
	cmp     #$00
	bne     L0845
	lda     _i
	cmp     #$0F
L0845:	bcs     L083F
;
; copyBgLine(map, mapCurrentLine + 15 + i);
;
	lda     #<(_map)
	ldx     #>(_map)
	jsr     pushax
	lda     _mapCurrentLine
	ldx     _mapCurrentLine+1
	clc
	adc     #$0F
	bcc     L0ADC
	inx
	clc
L0ADC:	adc     _i
	pha
	txa
	adc     _i+1
	tax
	pla
	jsr     _copyBgLine
;
; flushBGBuffer();
;
	ldy     #$00
	jsr     _flushBGBuffer
;
; for(i = 0; i < 15; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0847
	inx
L0847:	sta     _i
	stx     _i+1
	jmp     L083E
;
; PPU.vram.address = 0x23;
;
L083F:	lda     #$23
	sta     $2006
;
; PPU.vram.address = 0xC0;
;
	lda     #$C0
	sta     $2006
;
; for(i = 0; i < 64; i++) {
;
	lda     #$00
	sta     _i
	sta     _i+1
L0853:	lda     _i+1
	cmp     #$00
	bne     L085A
	lda     _i
	cmp     #$40
L085A:	bcs     L0854
;
; PPU.vram.data = 0x00;
;
	lda     #$00
	sta     $2007
;
; for(i = 0; i < 64; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L085C
	inx
L085C:	sta     _i
	stx     _i+1
	jmp     L0853
;
; PPU.vram.address = 0x2B;
;
L0854:	lda     #$2B
	sta     $2006
;
; PPU.vram.address = 0xC0;
;
	lda     #$C0
	sta     $2006
;
; for(i = 0; i < 64; i++) {
;
	lda     #$00
	sta     _i
	sta     _i+1
L0866:	lda     _i+1
	cmp     #$00
	bne     L086D
	lda     _i
	cmp     #$40
L086D:	bcs     L0867
;
; PPU.vram.data = 0xFF;
;
	lda     #$FF
	sta     $2007
;
; for(i = 0; i < 64; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L086F
	inx
L086F:	sta     _i
	stx     _i+1
	jmp     L0866
;
; }
;
L0867:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ drawMetaSprite (unsigned char, unsigned char, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_drawMetaSprite: near

.segment	"CODE"

;
; void __fastcall__ drawMetaSprite(uint8_t x, uint8_t y, const uint8_t *data) {
;
	jsr     pushax
;
; const uint8_t *ptr = data;
;
	jsr     pushw0sp
;
; while(*ptr != 127) {
;
	jmp     L089B
;
; if(x + *ptr < 255) {
;
L0899:	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1,x)
	jsr     tosadda0
	cpx     #$00
	bne     L089F
	cmp     #$FF
L089F:	jcs     L089D
;
; sprites[currentMetaSpriteId].x = x + *(ptr++);
;
	ldx     #$00
	lda     _currentMetaSpriteId
	jsr     aslax2
	clc
	adc     #<(_sprites)
	tay
	txa
	adc     #>(_sprites)
	tax
	tya
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L08A4
	inx
L08A4:	jsr     staxysp
	ldx     #$00
	lda     (regsave,x)
	jsr     tosadda0
	ldy     #$03
	jsr     staspidx
;
; sprites[currentMetaSpriteId].y = y + *(ptr++);
;
	ldx     #$00
	lda     _currentMetaSpriteId
	jsr     aslax2
	clc
	adc     #<(_sprites)
	tay
	txa
	adc     #>(_sprites)
	tax
	tya
	jsr     pushax
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L08A9
	inx
L08A9:	jsr     staxysp
	ldx     #$00
	lda     (regsave,x)
	jsr     tosadda0
	ldy     #$00
	jsr     staspidx
;
; sprites[currentMetaSpriteId].tile_index = *(ptr++);
;
	ldx     #$00
	lda     _currentMetaSpriteId
	jsr     aslax2
	clc
	adc     #<(_sprites)
	tay
	txa
	adc     #>(_sprites)
	tax
	tya
	jsr     pushax
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L08AE
	inx
L08AE:	jsr     staxysp
	ldy     #$00
	lda     (regsave),y
	iny
	jsr     staspidx
;
; sprites[currentMetaSpriteId].attributes = *(ptr++);
;
	ldx     #$00
	lda     _currentMetaSpriteId
	jsr     aslax2
	clc
	adc     #<(_sprites)
	tay
	txa
	adc     #>(_sprites)
	tax
	tya
	jsr     pushax
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L08B3
	inx
L08B3:	jsr     staxysp
	ldy     #$00
	lda     (regsave),y
	ldy     #$02
	jsr     staspidx
;
; currentMetaSpriteId++;
;
	lda     _currentMetaSpriteId
	clc
	adc     #$01
	sta     _currentMetaSpriteId
;
; } else {
;
	jmp     L089B
;
; ptr += 4; 
;
L089D:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
;
; while(*ptr != 127) {
;
L089B:	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1),y
	cmp     #$7F
	jne     L0899
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ drawSprite (unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_drawSprite: near

.segment	"CODE"

;
; void __fastcall__ drawSprite(uint8_t x, uint8_t y, uint8_t tile, uint8_t attr) {
;
	jsr     pusha
;
; sprites[currentMetaSpriteId].x = x;
;
	ldx     #$00
	lda     _currentMetaSpriteId
	jsr     aslax2
	clc
	adc     #<(_sprites)
	sta     ptr1
	txa
	adc     #>(_sprites)
	sta     ptr1+1
	ldy     #$03
	lda     (sp),y
	sta     (ptr1),y
;
; sprites[currentMetaSpriteId].y = y;
;
	ldx     #$00
	lda     _currentMetaSpriteId
	jsr     aslax2
	clc
	adc     #<(_sprites)
	sta     ptr1
	txa
	adc     #>(_sprites)
	sta     ptr1+1
	dey
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
;
; sprites[currentMetaSpriteId].tile_index = tile;
;
	ldx     #$00
	lda     _currentMetaSpriteId
	jsr     aslax2
	clc
	adc     #<(_sprites)
	sta     ptr1
	txa
	adc     #>(_sprites)
	sta     ptr1+1
	iny
	lda     (sp),y
	sta     (ptr1),y
;
; sprites[currentMetaSpriteId].attributes = attr;
;
	ldx     #$00
	lda     _currentMetaSpriteId
	jsr     aslax2
	clc
	adc     #<(_sprites)
	sta     ptr1
	txa
	adc     #>(_sprites)
	sta     ptr1+1
	dey
	lda     (sp),y
	ldy     #$02
	sta     (ptr1),y
;
; currentMetaSpriteId++;
;
	lda     _currentMetaSpriteId
	clc
	adc     #$01
	sta     _currentMetaSpriteId
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ initEntityList (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initEntityList: near

.segment	"CODE"

;
; for(i = 0; i < ENTITY_COUNT; i++) {
;
	lda     #$00
	sta     _i
	sta     _i+1
L08CB:	lda     _i+1
	cmp     #$00
	bne     L08D2
	lda     _i
	cmp     #$10
L08D2:	jcs     L08CC
;
; entities[i].x = 0;
;
	lda     _i
	ldx     _i+1
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
;
; entities[i].y = 0;
;
	lda     _i
	ldx     _i+1
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	iny
	sta     (ptr1),y
;
; entities[i].vx = 0;
;
	lda     _i
	ldx     _i+1
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	iny
	sta     (ptr1),y
;
; entities[i].vy = 0;
;
	lda     _i
	ldx     _i+1
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	iny
	sta     (ptr1),y
;
; entities[i].update = NULL;
;
	lda     _i
	ldx     _i+1
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	ldy     #$07
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; entities[i].health = 0;
;
	lda     _i
	ldx     _i+1
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	ldy     #$06
	sta     (ptr1),y
;
; entities[i].prev = i == 0? 0xFF : i - 1;
;
	lda     _i
	ldx     _i+1
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     _i
	ora     _i+1
	bne     L08EB
	lda     #$FF
	jmp     L0ADD
L08EB:	lda     _i
	sec
	sbc     #$01
L0ADD:	ldy     #$00
	sta     (ptr1),y
;
; entities[i].next = i == ENTITY_COUNT - 1 ? 0x0FF : i + 1;
;
	lda     _i
	ldx     _i+1
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     _i+1
	bne     L08F4
	lda     _i
	cmp     #$0F
	bne     L08F4
	lda     #$FF
	jmp     L0ADE
L08F4:	lda     _i
	clc
	adc     #$01
L0ADE:	iny
	sta     (ptr1),y
;
; for(i = 0; i < ENTITY_COUNT; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L08D4
	inx
L08D4:	sta     _i
	stx     _i+1
	jmp     L08CB
;
; freeEntityList = 0;
;
L08CC:	lda     #$00
	sta     _freeEntityList
;
; entityList = 0xFF;
;
	lda     #$FF
	sta     _entityList
;
; missileList = 0xFF;
;
	sta     _missileList
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ pushEntity (unsigned char, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_pushEntity: near

.segment	"CODE"

;
; void pushEntity(uint8_t id, uint8_t *list) {
;
	jsr     pushax
;
; if(*list != 0xFF) {
;
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1),y
	cmp     #$FF
	beq     L0900
;
; entities[id].next = *list;
;
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	iny
	jsr     staspidx
;
; entities[*list].prev = id;
;
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldx     #$00
	lda     (ptr1),y
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$02
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
;
; *list = id;
;
L0900:	iny
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$02
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ removeEntity (unsigned char, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_removeEntity: near

.segment	"CODE"

;
; void removeEntity(uint8_t id, uint8_t *list) {
;
	jsr     pushax
;
; if(*list == id) {
;
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldx     #$00
	lda     (ptr1),y
	ldy     #$02
	cmp     (sp),y
	bne     L0AE9
;
; if(entities[id].next == 0xFF) {
;
	lda     (sp),y
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	dey
	lda     (ptr1),y
	cmp     #$FF
	bne     L0AE7
;
; *list = 0xFF; // empty list
;
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$FF
	sta     (ptr1),y
;
; } else {
;
	jmp     L091C
;
; *list = entities[id].next;
;
L0AE7:	jsr     pushw0sp
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	dey
	jsr     staspidx
;
; entities[*list].prev = 0xFF;
;
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldx     #$00
	lda     (ptr1),y
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$FF
	sta     (ptr1),y
;
; } else {
;
	jmp     L091C
;
; entities[entities[id].prev].next = entities[id].next;
;
L0AE9:	lda     (sp),y
	jsr     mulax9
	sta     ptr1
	txa
	clc
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #<(_entities)
	ldx     #$00
	lda     (ptr1),y
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     staspidx
;
; entities[id].next = 0xFF;
;
L091C:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$FF
	dey
	sta     (ptr1),y
;
; entities[id].prev = 0xFF;
;
	iny
	ldx     #$00
	lda     (sp),y
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ popEntity (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_popEntity: near

.segment	"CODE"

;
; uint8_t popEntity(uint8_t *list) {
;
	jsr     pushax
;
; uint8_t newId = *list;
;
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1),y
	jsr     pusha
;
; removeEntity(newId, list);
;
	ldy     #$00
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _removeEntity
;
; return newId;
;
	ldx     #$00
	lda     (sp,x)
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ bulletUpdate (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bulletUpdate: near

.segment	"CODE"

;
; entities[currentEntityId].x += entities[currentEntityId].vx;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     pusha0
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$04
	jsr     ldaidx
	jsr     tosaddax
	ldy     #$02
	jsr     staspidx
;
; entities[currentEntityId].y += entities[currentEntityId].vy;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     pusha0
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	jsr     tosaddax
	ldy     #$03
	jsr     staspidx
;
; if(entities[currentEntityId].vy < 0 && entities[currentEntityId].y + entities[currentEntityId].vy > entities[currentEntityId].y) {
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	asl     a
	bcc     L0937
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     pusha0
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     tosicmp0
	beq     L0937
	bcc     L0937
;
; removeEntity(currentEntityId, &entityList);
;
	lda     _currentEntityId
	jsr     pusha
	lda     #<(_entityList)
	ldx     #>(_entityList)
	jsr     _removeEntity
;
; pushEntity(currentEntityId, &freeEntityList);
;
	lda     _currentEntityId
	jsr     pusha
	lda     #<(_freeEntityList)
	ldx     #>(_freeEntityList)
	jsr     _pushEntity
;
; drawSprite(entities[currentEntityId].x, entities[currentEntityId].y, 0x60, 0x00);
;
L0937:	jsr     decsp3
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	sta     (sp),y
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	iny
	lda     (ptr1),y
	ldy     #$01
	sta     (sp),y
	lda     #$60
	dey
	sta     (sp),y
	tya
	jmp     _drawSprite

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ spawnBullet (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spawnBullet: near

.segment	"BSS"

L094D:
	.res	1,$00

.segment	"CODE"

;
; void __fastcall__ spawnBullet(uint8_t x, uint8_t y) {
;
	jsr     pusha
;
; id = popEntity(&freeEntityList);
;
	lda     #<(_freeEntityList)
	ldx     #>(_freeEntityList)
	jsr     _popEntity
	sta     L094D
;
; if(id != 0xFF) {
;
	cmp     #$FF
	bne     L0AEC
;
; }
;
	jmp     incsp2
;
; pushEntity(id, &entityList);
;
L0AEC:	lda     L094D
	jsr     pusha
	lda     #<(_entityList)
	ldx     #>(_entityList)
	jsr     _pushEntity
;
; entities[id].x = x;
;
	ldx     #$00
	lda     L094D
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$01
	lda     (sp),y
	iny
	sta     (ptr1),y
;
; entities[id].y = y;
;
	ldx     #$00
	lda     L094D
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	ldy     #$03
	sta     (ptr1),y
;
; entities[id].vx = 0;
;
	ldx     #$00
	lda     L094D
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	iny
	sta     (ptr1),y
;
; entities[id].vy = -4;
;
	tax
	lda     L094D
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$FC
	iny
	sta     (ptr1),y
;
; entities[id].health = 255;
;
	ldx     #$00
	lda     L094D
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$FF
	iny
	sta     (ptr1),y
;
; entities[id].update = bulletUpdate;
;
	ldx     #$00
	lda     L094D
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #<(_bulletUpdate)
	iny
	sta     (ptr1),y
	iny
	lda     #>(_bulletUpdate)
	sta     (ptr1),y
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ playerUpdate (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_playerUpdate: near

.segment	"CODE"

;
; if(InputPort1 & BUTTON_UP) {
;
	lda     _InputPort1
	and     #$08
	beq     L0AEE
;
; if (entities[currentEntityId].vy > -6) {
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	sec
	sbc     #$FB
	bvs     L096E
	eor     #$80
L096E:	jpl     L0AF2
;
; entities[currentEntityId].vy -= 1;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	ldy     #$05
	jsr     ldaidx
	sec
	sbc     #$01
	jsr     staspidx
;
; else if(InputPort1 & BUTTON_DOWN) {
;
	jmp     L0AF2
L0AEE:	lda     _InputPort1
	ldx     #$00
	and     #$04
	beq     L0AEF
;
; if (entities[currentEntityId].vy < 6) {
;
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	sec
	sbc     #$06
	bvc     L0978
	eor     #$80
L0978:	jpl     L0AF2
;
; entities[currentEntityId].vy += 1;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	ldy     #$05
	jsr     ldaidx
	clc
	adc     #$01
	jsr     staspidx
;
; } else if(entities[currentEntityId].vy > 2) {
;
	jmp     L0AF2
L0AEF:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	sec
	sbc     #$03
	bvs     L0980
	eor     #$80
L0980:	asl     a
	ldx     #$00
	bcc     L0AF0
;
; entities[currentEntityId].vy -= 2;
;
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	ldy     #$05
	jsr     ldaidx
	sec
	sbc     #$02
	jsr     staspidx
;
; } else if(entities[currentEntityId].vy < -2) {
;
	jmp     L0AF2
L0AF0:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	sec
	sbc     #$FE
	bvc     L0988
	eor     #$80
L0988:	asl     a
	ldx     #$00
	bcc     L0AF1
;
; entities[currentEntityId].vy += 2;
;
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	ldy     #$05
	jsr     ldaidx
	clc
	adc     #$02
	jsr     staspidx
;
; } else {
;
	jmp     L0AF2
;
; entities[currentEntityId].vy = 0;
;
L0AF1:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	sta     (ptr1),y
;
; if(InputPort1 & BUTTON_LEFT) {
;
L0AF2:	lda     _InputPort1
	and     #$02
	beq     L0AF3
;
; if (entities[currentEntityId].vx > -6) {
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$04
	jsr     ldaidx
	sec
	sbc     #$FB
	bvs     L0995
	eor     #$80
L0995:	jpl     L0AF7
;
; --entities[currentEntityId].vx;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     (ptr1),y
	sec
	sbc     #$01
;
; } else if(InputPort1 & BUTTON_RIGHT) {
;
	jmp     L0AED
L0AF3:	lda     _InputPort1
	ldx     #$00
	and     #$01
	beq     L0AF4
;
; if (entities[currentEntityId].vx < 6) {
;
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$04
	jsr     ldaidx
	sec
	sbc     #$06
	bvc     L099E
	eor     #$80
L099E:	jpl     L0AF7
;
; ++entities[currentEntityId].vx;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$01
	clc
	adc     (ptr1),y
;
; } else if(entities[currentEntityId].vx > 2) {
;
	jmp     L0AED
L0AF4:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$04
	jsr     ldaidx
	sec
	sbc     #$03
	bvs     L09A5
	eor     #$80
L09A5:	asl     a
	ldx     #$00
	bcc     L0AF5
;
; entities[currentEntityId].vx -= 2;
;
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	ldy     #$04
	jsr     ldaidx
	sec
	sbc     #$02
	jsr     staspidx
;
; } else if(entities[currentEntityId].vx < -2) {
;
	jmp     L0AF7
L0AF5:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$04
	jsr     ldaidx
	sec
	sbc     #$FE
	bvc     L09AD
	eor     #$80
L09AD:	asl     a
	ldx     #$00
	bcc     L0AF6
;
; entities[currentEntityId].vx += 2;
;
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	ldy     #$04
	jsr     ldaidx
	clc
	adc     #$02
	jsr     staspidx
;
; } else {
;
	jmp     L0AF7
;
; entities[currentEntityId].vx = 0;
;
L0AF6:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
L0AED:	sta     (ptr1),y
;
; if((InputPort1 & BUTTON_B) && !(InputPort1Prev & BUTTON_B)) {
;
L0AF7:	lda     _InputPort1
	ldx     #$00
	and     #$40
	beq     L0AFB
	lda     _InputPort1Prev
	and     #$40
	bne     L0AFB
;
; spawnBullet(entities[currentEntityId].x + 4, entities[currentEntityId].y + 8);
;
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	clc
	adc     #$04
	jsr     pusha
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	clc
	adc     #$08
	jsr     _spawnBullet
;
; if(entities[currentEntityId].vy < 0 && entities[currentEntityId].y + entities[currentEntityId].vy > entities[currentEntityId].y) {
;
	ldx     #$00
L0AFB:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	asl     a
	ldx     #$00
	jcc     L0AFE
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     pusha0
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     tosicmp0
	beq     L0B04
	bcc     L0B04
;
; entities[currentEntityId].y = 0;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	ldy     #$03
	sta     (ptr1),y
;
; entities[currentEntityId].vy = 0;
;
	tax
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	ldy     #$05
	sta     (ptr1),y
;
; if(entities[currentEntityId].y + entities[currentEntityId].vy > 218) {
;
L0B04:	ldx     #$00
L0AFE:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     pusha0
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	jsr     tosaddax
	cmp     #$DB
	txa
	sbc     #$00
	ldx     #$00
	bcc     L0AFF
;
; entities[currentEntityId].y = 218;
;
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$DA
	ldy     #$03
	sta     (ptr1),y
;
; entities[currentEntityId].vy = 0;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	ldy     #$05
	sta     (ptr1),y
;
; if(entities[currentEntityId].vx < 0 && entities[currentEntityId].x + entities[currentEntityId].vx > entities[currentEntityId].x) {
;
	tax
L0AFF:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$04
	jsr     ldaidx
	asl     a
	ldx     #$00
	jcc     L0B02
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     pusha0
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$04
	jsr     ldaidx
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     tosicmp0
	beq     L0B05
	bcc     L0B05
;
; entities[currentEntityId].x = 0;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	ldy     #$02
	sta     (ptr1),y
;
; entities[currentEntityId].vx = 0;
;
	tax
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	ldy     #$04
	sta     (ptr1),y
;
; if(entities[currentEntityId].x + entities[currentEntityId].vx > 240) {
;
L0B05:	ldx     #$00
L0B02:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     pusha0
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$04
	jsr     ldaidx
	jsr     tosaddax
	cmp     #$F1
	txa
	sbc     #$00
	ldx     #$00
	bcc     L0B03
;
; entities[currentEntityId].x = 240;
;
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$F0
	ldy     #$02
	sta     (ptr1),y
;
; entities[currentEntityId].vx = 0;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	ldy     #$04
	sta     (ptr1),y
;
; entities[currentEntityId].x += entities[currentEntityId].vx;
;
	tax
L0B03:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     pusha0
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$04
	jsr     ldaidx
	jsr     tosaddax
	ldy     #$02
	jsr     staspidx
;
; entities[currentEntityId].y += entities[currentEntityId].vy;
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     pusha0
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	tay
	txa
	adc     #>(_entities)
	tax
	tya
	ldy     #$05
	jsr     ldaidx
	jsr     tosaddax
	ldy     #$03
	jsr     staspidx
;
; drawMetaSprite(entities[currentEntityId].x, entities[currentEntityId].y, playerSpriteFrames[(FrameCount >> 3) & 0x01]);
;
	jsr     decsp2
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	dey
	sta     (sp),y
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	ldy     #$00
	sta     (sp),y
	lda     _FrameCount
	lsr     a
	lsr     a
	lsr     a
	and     #$01
	jsr     pusha0
	lda     #$11
	jsr     tosmula0
	clc
	adc     #<(_playerSpriteFrames)
	tay
	txa
	adc     #>(_playerSpriteFrames)
	tax
	tya
	jmp     _drawMetaSprite

.endproc

; ---------------------------------------------------------------
; void __near__ loadPalette (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_loadPalette: near

.segment	"CODE"

;
; void loadPalette(const uint8_t *pal) {
;
	jsr     pushax
;
; PPU.vram.address = 0x3f;
;
	lda     #$3F
	sta     $2006
;
; PPU.vram.address = 0x00;
;
	lda     #$00
	sta     $2006
;
; for ( i = 0; i < 32; ++i ) {
;
	sta     _i
	sta     _i+1
L0A09:	lda     _i+1
	cmp     #$00
	bne     L0A10
	lda     _i
	cmp     #$20
L0A10:	bcs     L0A0A
;
; PPU.vram.data = pal[i];
;
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     _i
	sta     ptr1
	txa
	adc     _i+1
	sta     ptr1+1
	lda     (ptr1),y
	sta     $2007
;
; for ( i = 0; i < 32; ++i ) {
;
	inc     _i
	bne     L0A09
	inc     _i+1
	jmp     L0A09
;
; }
;
L0A0A:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; APU.status = 0x0F;
;
	jsr     decsp1
	lda     #$0F
	sta     $4015
;
; bankswitch(1);
;
	lda     #$01
	jsr     _bankswitch
;
; loadPalette(titlePalette);
;
	lda     #<(_titlePalette)
	ldx     #>(_titlePalette)
	jsr     _loadPalette
;
; copyTitleScreen();
;
	jsr     _copyTitleScreen
;
; Scroll = 239;
;
	ldx     #$00
	lda     #$EF
	sta     _Scroll
	stx     _Scroll+1
;
; timer = 0;
;
	txa
	sta     _timer
	sta     _timer+1
;
; VRAMUpdateReady = 1;
;
	lda     #$01
	sta     _VRAMUpdateReady
;
; PPU.control = PPUCTRL_NAMETABLE_0 | PPUCTRL_INC_1_HORIZ | PPUCTRL_BPATTERN_0 | PPUCTRL_SPATTERN_1 | PPUCTRL_NMI_ON;
;
	lda     #$88
	sta     $2000
;
; while (!endLoop) {
;
	jmp     L0A2C
;
; WaitFrame();
;
L0A2A:	jsr     _WaitFrame
;
; if(timer > 32) {
;
	lda     _timer
	cmp     #$21
	lda     _timer+1
	sbc     #$00
	bcc     L0A2F
;
; Scroll = 0;
;
	lda     #$00
	sta     _Scroll
	sta     _Scroll+1
;
; PPU.vram.address = 0x3f;
;
	lda     #$3F
	sta     $2006
;
; PPU.vram.address = 0x0B;
;
	lda     #$0B
	sta     $2006
;
; PPU.vram.data = (((FrameCount >> 2) & 0x03) << 4) + 0x06;
;
	lda     _FrameCount
	lsr     a
	lsr     a
	and     #$03
	asl     a
	asl     a
	asl     a
	asl     a
	clc
	adc     #$06
	sta     $2007
;
; PPU.vram.address = 0x00;
;
	lda     #$00
	sta     $2006
;
; PPU.vram.address = 0x00;
;
	sta     $2006
;
; if((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
	lda     _InputPort1
	and     #$10
	beq     L0A2C
	lda     _InputPort1Prev
	and     #$10
	bne     L0A2C
;
; endLoop = 1;
;
	lda     #$01
	sta     _endLoop
;
; } else {
;
	jmp     L0A2C
;
; ++timer;
;
L0A2F:	inc     _timer
	bne     L0A50
	inc     _timer+1
;
; if(Scroll > 0) 
;
L0A50:	lda     _Scroll
	ora     _Scroll+1
	beq     L0A51
;
; Scroll -= 16;
;
	lda     _Scroll
	sec
	sbc     #$10
	sta     _Scroll
	bcs     L0A51
	dec     _Scroll+1
;
; if(Scroll > 0x100)
;
L0A51:	lda     _Scroll
	cmp     #$01
	lda     _Scroll+1
	sbc     #$01
	bcc     L0A2C
;
; Scroll = 0;
;
	lda     #$00
	sta     _Scroll
	sta     _Scroll+1
;
; while (!endLoop) {
;
L0A2C:	lda     _endLoop
	jeq     L0A2A
;
; WaitFrame();
;
	jsr     _WaitFrame
;
; PPU.control = PPUCTRL_NAMETABLE_0 | PPUCTRL_INC_1_HORIZ | PPUCTRL_BPATTERN_0 | PPUCTRL_SPATTERN_1 | PPUCTRL_NMI_OFF;
;
	lda     #$08
	sta     $2000
;
; PPU.mask = 0;
;
	lda     #$00
	sta     $2001
;
; bankswitch(0);
;
	jsr     _bankswitch
;
; loadPalette(mapPalette);
;
	lda     #<(_mapPalette)
	ldx     #>(_mapPalette)
	jsr     _loadPalette
;
; initEntityList();
;
	jsr     _initEntityList
;
; fillBackground();
;
	jsr     _fillBackground
;
; playerId = popEntity(&freeEntityList);
;
	lda     #<(_freeEntityList)
	ldx     #>(_freeEntityList)
	jsr     _popEntity
	ldy     #$00
	sta     (sp),y
;
; pushEntity(playerId, &entityList);
;
	jsr     pusha
	lda     #<(_entityList)
	ldx     #>(_entityList)
	jsr     _pushEntity
;
; entities[playerId].x = 64;
;
	ldx     #$00
	lda     (sp,x)
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$40
	ldy     #$02
	sta     (ptr1),y
;
; entities[playerId].y = 128;
;
	ldx     #$00
	lda     (sp,x)
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$80
	iny
	sta     (ptr1),y
;
; entities[playerId].vx = 0;
;
	ldx     #$00
	lda     (sp,x)
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	iny
	sta     (ptr1),y
;
; entities[playerId].vy = 0;
;
	tax
	lda     (sp,x)
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$00
	iny
	sta     (ptr1),y
;
; entities[playerId].health = 255;
;
	tax
	lda     (sp,x)
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #$FF
	iny
	sta     (ptr1),y
;
; entities[playerId].update = playerUpdate;
;
	ldx     #$00
	lda     (sp,x)
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	lda     #<(_playerUpdate)
	iny
	sta     (ptr1),y
	iny
	lda     #>(_playerUpdate)
	sta     (ptr1),y
;
; VRAMUpdateReady = 1;
;
	lda     #$01
	sta     _VRAMUpdateReady
;
; PPU.control = PPUCTRL_NAMETABLE_0 | PPUCTRL_INC_1_HORIZ | PPUCTRL_BPATTERN_0 | PPUCTRL_SPATTERN_1 | PPUCTRL_NMI_ON;
;
	lda     #$88
	sta     $2000
;
; Scroll = 0x108;
;
	ldx     #$01
	sty     _Scroll
	stx     _Scroll+1
;
; endLoop = 0;
;
	lda     #$00
	sta     _endLoop
;
; while (!endLoop) {
;
	jmp     L0A8C
;
; WaitFrame();
;
L0A8A:	jsr     _WaitFrame
;
; currentMetaSpriteId = 0; // might be done in nmi?
;
	lda     #$00
	sta     _currentMetaSpriteId
;
; if(!(FrameCount & 0x00) && mapCurrentLine != 0xFFFF) { // stop when mapCurrentLine == -1
;
	lda     _mapCurrentLine+1
	cmp     #$FF
	bne     L0B0B
	lda     _mapCurrentLine
	cmp     #$FF
	jeq     L0B12
;
; if(Scroll > 0) {
;
L0B0B:	lda     _Scroll
	ora     _Scroll+1
	beq     L0A97
;
; --Scroll;
;
	lda     _Scroll
	sec
	sbc     #$01
	sta     _Scroll
	bcs     L0A9B
	dec     _Scroll+1
;
; if(Scroll == 255) {
;
L0A9B:	lda     _Scroll+1
	bne     L0AA1
	lda     _Scroll
	cmp     #$FF
	bne     L0AA1
;
; Scroll = 239;
;
	ldx     #$00
;
; } else {
;
	jmp     L0B14
;
; Scroll = 256 + 239;
;
L0A97:	ldx     #$01
L0B14:	lda     #$EF
	sta     _Scroll
	stx     _Scroll+1
;
; if((Scroll & 0x0F) == 0x0F && mapCurrentLine != 0xFFFF) {
;
L0AA1:	lda     _Scroll
	ldx     #$00
	and     #$0F
	cmp     #$0F
	bne     L0B0F
	lda     _mapCurrentLine+1
	cmp     #$FF
	bne     L0B0D
	lda     _mapCurrentLine
	cmp     #$FF
	beq     L0B0F
;
; --mapCurrentLine;
;
L0B0D:	lda     _mapCurrentLine
	sec
	sbc     #$01
	sta     _mapCurrentLine
	bcs     L0AAC
	dec     _mapCurrentLine+1
;
; copyBgLine(map, mapCurrentLine);
;
L0AAC:	lda     #<(_map)
	ldx     #>(_map)
	jsr     pushax
	lda     _mapCurrentLine
	ldx     _mapCurrentLine+1
	jsr     _copyBgLine
;
; BGDestAddr = (Scroll > 240 ? 0x2800 : 0x2000) + (((Scroll & 0xFF) >> 4) << 6);
;
	lda     _Scroll
	cmp     #$F1
	lda     _Scroll+1
	sbc     #$00
	lda     #$00
	bcc     L0AB3
	ldx     #$28
	jmp     L0B0E
L0AB3:	ldx     #$20
L0B0E:	sta     ptr1
	stx     ptr1+1
	lda     _Scroll
	ldx     #$00
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	jsr     shlax4
	jsr     shlax2
	clc
	adc     ptr1
	sta     _BGDestAddr
	txa
	adc     ptr1+1
	sta     _BGDestAddr+1
;
; currentEntityId = entityList;
;
L0B12:	ldx     #$00
L0B0F:	lda     _entityList
	sta     _currentEntityId
;
; while(currentEntityId != 0xFF) {
;
	jmp     L0B11
;
; uint8_t next = entities[currentEntityId].next;
;
L0B10:	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     pusha
;
; entities[currentEntityId].update();
;
	ldx     #$00
	lda     _currentEntityId
	jsr     mulax9
	clc
	adc     #<(_entities)
	sta     ptr1
	txa
	adc     #>(_entities)
	sta     ptr1+1
	ldy     #$08
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     callax
;
; currentEntityId = next;
;
	ldy     #$00
	lda     (sp),y
	sta     _currentEntityId
;
; }
;
	jsr     incsp1
;
; while(currentEntityId != 0xFF) {
;
	ldx     #$00
L0B11:	lda     _currentEntityId
	cmp     #$FF
	bne     L0B10
;
; for(i = currentMetaSpriteId; i < 64; i++) {
;
	lda     _currentMetaSpriteId
	sta     _i
	stx     _i+1
L0AC6:	lda     _i+1
	cmp     #$00
	bne     L0ACD
	lda     _i
	cmp     #$40
L0ACD:	bcs     L0AC7
;
; sprites[i].y = 240;
;
	lda     _i
	ldx     _i+1
	jsr     aslax2
	clc
	adc     #<(_sprites)
	sta     ptr1
	txa
	adc     #>(_sprites)
	sta     ptr1+1
	lda     #$F0
	ldy     #$00
	sta     (ptr1),y
;
; for(i = currentMetaSpriteId; i < 64; i++) {
;
	lda     _i
	ldx     _i+1
	clc
	adc     #$01
	bcc     L0ACF
	inx
L0ACF:	sta     _i
	stx     _i+1
	jmp     L0AC6
;
; VRAMUpdateReady = 1;
;
L0AC7:	lda     #$01
	sta     _VRAMUpdateReady
;
; while (!endLoop) {
;
L0A8C:	lda     _endLoop
	jeq     L0A8A
;
; };
;
	jmp     incsp1

.endproc

